### ISSUE TITLE
Start likelihood:-Infinity after 50 initialisation attempts

### ISSUE THREAD

**Issue by Omnipotent32** [denisekuehnert/bdmm#33]
Hi, I'm a fresh guy in using BDMM. I want to calculate the R0 of 5 large HIV-1 clusters identified by transmission network analysis, so I set the cluster serial number as demes. All I need to analyze are 5 cluster, then I set demes to 5. After finished other settings, I ran the BEAST, the I have the next warning. Could anyone tell me how to figure out this problem?
![5MOTBP7VX5MO%8ZN)U2S0ED](https://user-images.githubusercontent.com/48283242/100742240-6fd32c00-3415-11eb-92a8-9ff27e71618a.png)
![GNDCJ~ 86M2BXN1Z$ @JMPX](https://user-images.githubusercontent.com/48283242/100742249-72358600-3415-11eb-961b-98432da3e2ec.png)

**Comment by Omnipotent32** [comment]
Oh the problem is done, I found I set the wrong sampling change time which not early than the height of the first sample

**Comment by ntakebay** [comment]
I'm having a similar problem.  I'm trying to follow BDMM Beginner's Tutorial: <https://github.com/denisekuehnert/bdmm/wiki/Beginner's-Tutorial> with BEAST 2.6.7.

I think I followed BEAUti configuration there, but I get the same error as Omnipotent32:

P(birthDeathMigration.t:h3n2_2deme) = -Infinity (was -Infinity)

The first figure in [Adjusting Priors section](https://github.com/denisekuehnert/bdmm/wiki/Beginner's-Tutorial#adjusting-priors) has "Sampling change time:" of 2.63, but the paragraph before that seems to indicate that this value should be 5.57.  I tried 2.63 and 5.57, but they give the same error.

What am I doing wrong?

Thank you, Naoki

Below is some relevant part of error message.

                      BEAST v2.6.7, 2002-2022

:
:
Random number seed: 1668648561137

Alignment(h3n2_2deme)
  60 taxa
  1762 sites
  211 patterns

CY002938_NewZealand_2004.68767123 = NewZealand (NaN)
CY007011_NewZealand_2003.61917808 = NewZealand (NaN)
CY007059_NewZealand_2003.50958904 = NewZealand (NaN)
CY007203_NewZealand_2003.53972603 = NewZealand (NaN)
CY007227_NewZealand_2003.54246575 = NewZealand (NaN)
CY007267_NewZealand_2003.62739726 = NewZealand (NaN)
CY007395_NewZealand_2004.63287671 = NewZealand (NaN)
CY007667_NewZealand_2002.35616438 = NewZealand (NaN)
CY007795_NewZealand_2005.17534247 = NewZealand (NaN)
CY007923_NewZealand_2002.48219178 = NewZealand (NaN)
50 more...
CY002938_NewZealand_2004.68767123 = 2004.68767123 (0.9808219199999257)
CY007011_NewZealand_2003.61917808 = 2003.61917808 (2.0493150699999205)
CY007059_NewZealand_2003.50958904 = 2003.50958904 (2.1589041099998667)
CY007203_NewZealand_2003.53972603 = 2003.53972603 (2.128767119999793)
CY007227_NewZealand_2003.54246575 = 2003.54246575 (2.1260273999998844)
CY007267_NewZealand_2003.62739726 = 2003.62739726 (2.0410958899999514)
CY007395_NewZealand_2004.63287671 = 2004.63287671 (1.0356164400000125)
CY007667_NewZealand_2002.35616438 = 2002.35616438 (3.3123287699997945)
CY007795_NewZealand_2005.17534247 = 2005.17534247 (0.4931506799998715)
CY007923_NewZealand_2002.48219178 = 2002.48219178 (3.18630136999991)
50 more...
  Using BEAGLE version: 4.0.0 (PRE-RELEASE) resource 0: CPU (x86_64)
    with instance flags:  PRECISION_DOUBLE COMPUTATION_SYNCH EIGEN_REAL SCALING_MANUAL SCALERS_RAW VECTOR_SSE THREADING_NONE PROCESSOR_CPU FRAMEWORK_CPU
===============================================================================

:
:

===============================================================================
Start likelihood: -Infinity after 10 initialisation attempts
P(posterior) = -Infinity (was -Infinity)
	P(prior) = -Infinity (was -Infinity)
		P(birthDeathMigration.t:h3n2_2deme) = -Infinity (was -Infinity)
		P(RPrior.t:h3n2_2deme) = -3.7046244414474376 (was -3.7046244414474376)
		P(becomeUninfectiousRatePrior.t:h3n2_2deme) = -1.8378770664093453 (was -1.8378770664093453)
		P(ClockPrior.c:h3n2_2deme) = 0.0 (was 0.0)
		P(FrequenciesPrior.s:h3n2_2deme) = 0.0 (was 0.0)
		P(GammaShapePrior.s:h3n2_2deme) = -1.0 (was -1.0)
		P(KappaPrior.s:h3n2_2deme) = -1.8653600339742873 (was -1.8653600339742873)
		P(PropInvariantPrior.s:h3n2_2deme) = 0.0 (was 0.0)
		P(rateMatrixPrior.t:h3n2_2deme) = -0.2 (was -0.2)
		P(samplingProportionPrior.t:h3n2_2deme) = 1.7763568394002497E-15 (was 1.7763568394002497E-15)
	P(likelihood) = NaN (was NaN)  **
		P(treeLikelihood.h3n2_2deme) = NaN (was NaN)  **
Fatal exception: Could not find a proper state to initialise. Perhaps try another seed.
See http://www.beast2.org/2018/07/04/fatal-errors.html for other possible solutions.
java.lang.RuntimeException: Could not find a proper state to initialise. Perhaps try another seed.
See http://www.beast2.org/2018/07/04/fatal-errors.html for other possible solutions.
	at beast.core.MCMC.run(Unknown Source)
	at beast.app.BeastMCMC.run(Unknown Source)
	at beast.app.beastapp.BeastMain.<init>(Unknown Source)
	at beast.app.beastapp.BeastMain.main(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at beast.app.beastapp.BeastLauncher.run(Unknown Source)
	at beast.app.beastapp.BeastLauncher.main(Unknown Source)
Fatal exception: Could not find a proper state to initialise. Perhaps try another seed.
See http://www.beast2.org/2018/07/04/fatal-errors.html for other possible solutions.

BEAST has terminated with an error. Please select QUIT from the menu.
